CREATE TABLE `admin_ac` (
  `id` int(11) NOT NULL,
  `wingo1` text NOT NULL,
  `wingo3` text NOT NULL,
  `wingo5` text NOT NULL,
  `wingo10` text NOT NULL,
  `k5d` text NOT NULL,
  `k5d3` text NOT NULL,
  `k5d5` text,
  `k5d10` text NOT NULL,
  `k3d` text NOT NULL,
  `k3d3` text NOT NULL,
  `k3d5` text NOT NULL,
  `k3d10` text NOT NULL,
  `win_rate` int(11) NOT NULL DEFAULT 0,
  `telegram` varchar(100) NOT NULL DEFAULT '0',
  `cskh` varchar(100) NOT NULL DEFAULT '0',
  `app` text,
  `recharge_bonus` int(11) DEFAULT NULL,
  `recharge_bonus_2` int(11) DEFAULT NULL,
  `app_name` text NOT NULL,
  `app_about` text NOT NULL,
  `app_notification` text NOT NULL,
  `notice1` text NOT NULL,
  `notice2` text NOT NULL,
  `notice3` text NOT NULL,
  `BONUS_MONEY_ON_REGISTER` int(10) NOT NULL DEFAULT 0,
  `MINIMUM_MONEY_USDT` int(10) NOT NULL DEFAULT 0,
  `MINIMUM_MONEY_INR` int(10) NOT NULL DEFAULT 0,
  `MINIMUM_WITHDRAWAL_MONEY_USDT` int(10) NOT NULL DEFAULT 0,
  `MINIMUM_WITHDRAWAL_MONEY_INR` int(10) NOT NULL DEFAULT 0,
  `USDT_INR_EXCHANGE_RATE` int(10) NOT NULL DEFAULT 0,
  `INVITER_BONUS_MONEY_ON_REGISTER` int(10) NOT NULL DEFAULT 0,
  `usr_rech_bonus` int(10) NOT NULL DEFAULT 0,
  `inv_rech_bonus` int(10) NOT NULL DEFAULT 0,
  `r3` int(10) NOT NULL DEFAULT 0,
  `mininrdep` varchar(10) NOT NULL DEFAULT '0',
  `minusdtdep` varchar(10) NOT NULL DEFAULT '0',
  `mininrwit` varchar(10) NOT NULL DEFAULT '0',
  `minusdtwit` varchar(10) NOT NULL DEFAULT '0',
  `inrusdtrate` varchar(10) NOT NULL DEFAULT '0',
  `minfirstrech` varchar(10) NOT NULL DEFAULT '0',
  `safeinterest` varchar(10) NOT NULL DEFAULT '0',
  `r4` varchar(10) NOT NULL DEFAULT '0'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_general_ci;
